//! Turning one JSON Schema object into prompts and a request body.
//!
//! The service generates the schemas for `config`, `credentials` and `selector`
//! from the models that validate the request, so this module reads the label,
//! the help text, the accepted values, the default, and — through
//! `format: password` — which answers must never be echoed, straight off the
//! wire. A field the service renamed changes the prompt; a field it dropped
//! stops being asked; a value it stopped accepting stops being offered.
//!
//! **What the schema does not give**, and what therefore lives in the caller:
//! the ORDER to ask in, which fields to GROUP, and which to ask only once an
//! earlier answer is known. Those are per-family flows written by hand in
//! `datasource_wizard`; nothing here pretends they are generated.
//!
//! Two invariants hold the two halves together:
//!
//! - [`Form::ask`] on a key the schema does not describe is a no-op, so a hand-
//!   written flow can never prompt for a field the API would 422.
//! - [`Form::ask_remaining_required`] sweeps up every required field the flow
//!   did not name, so a newly-required field cannot make the wizard build an
//!   incomplete body while the flow waits to be updated.

use crate::commands::prompt;

/// How a field's answer is collected and typed.
#[derive(Debug, PartialEq)]
pub enum FieldKind {
    Text,
    Integer,
    Boolean,
    /// `["a", "b"]` — asked as a comma-separated list.
    StringList,
    /// A free-form map. Has no fields of its own to prompt, so it is filled
    /// from a hint rather than by [`Form::ask`].
    Map,
}

/// One promptable field, as the schema describes it.
#[derive(Debug)]
pub struct FieldSpec {
    pub label: String,
    pub help: Option<String>,
    pub required: bool,
    /// `format: password`. Hidden input, and never carried into a default.
    pub secret: bool,
    /// `enum` members — asked as a menu rather than typed.
    pub choices: Vec<String>,
    pub default: Option<String>,
    pub kind: FieldKind,
}

/// The schema for one property, with the optionality wrapper removed.
///
/// An optional field arrives as `anyOf: [T, {"type": "null"}]`, so reading
/// `type`/`format`/`enum` off the outer object finds nothing for exactly the
/// fields most likely to be optional — every credential, in practice.
fn unwrapped(prop: &serde_json::Value) -> &serde_json::Value {
    prop.get("anyOf")
        .and_then(|a| a.as_array())
        .and_then(|members| {
            members
                .iter()
                .find(|m| m.get("type").and_then(|t| t.as_str()) != Some("null"))
        })
        .unwrap_or(prop)
}

/// Name fragments that make an answer a secret whatever the schema says.
///
/// `_key` is handled as a SUFFIX rather than a fragment because it only means a
/// secret at the end of a name: `aws_secret_access_key` is one,
/// `aws_access_key_id` is the public half of the same credential and reads as
/// gibberish behind asterisks.
const SECRET_NAME_PARTS: [&str; 7] = [
    "password",
    "passwd",
    "passphrase",
    "secret",
    "token",
    "credential",
    "authorization",
];

/// Whether this property is a secret: what the schema says, or failing that,
/// what the field is called.
///
/// `format: password` is the service's own answer and normally decides. The
/// name check behind it is there because that answer arrives over the NETWORK,
/// and it is the only thing standing between a credential and a prompt that
/// prints it: a credential field added without the marker, or a schema
/// regenerated by a library that drops unknown keywords, turns the masked
/// prompt into an echoing one with nothing failing — and the plaintext then
/// sits in the user's scrollback, where rotating the credential cannot reach
/// it.
///
/// The two rules can only disagree in the safe direction. A non-secret field
/// named like a secret gets masked, costing the user the ability to read back
/// what they typed; the converse costs them the secret. Identity halves are
/// excluded on purpose: a name ending `_id` is the public part of a credential
/// pair (`aws_access_key_id`, `client_id`, `tenant_id`), which the service also
/// declines to mark.
fn is_secret_field(key: &str, prop: &serde_json::Value) -> bool {
    let password =
        |v: &serde_json::Value| v.get("format").and_then(|f| f.as_str()) == Some("password");
    if password(prop) || password(unwrapped(prop)) {
        return true;
    }
    let name = key.to_ascii_lowercase();
    if name.ends_with("_id") {
        return false;
    }
    name.ends_with("_key") || SECRET_NAME_PARTS.iter().any(|part| name.contains(part))
}

/// A property's `enum` members as display strings.
fn choices(prop: &serde_json::Value) -> Vec<String> {
    let inner = unwrapped(prop);
    inner
        .get("enum")
        .or_else(|| prop.get("enum"))
        .and_then(|e| e.as_array())
        .map(|members| members.iter().map(scalar).collect())
        .unwrap_or_default()
}

fn kind_of(prop: &serde_json::Value) -> FieldKind {
    let inner = unwrapped(prop);
    match inner.get("type").and_then(|t| t.as_str()) {
        Some("integer") | Some("number") => FieldKind::Integer,
        Some("boolean") => FieldKind::Boolean,
        Some("array") => FieldKind::StringList,
        Some("object") => FieldKind::Map,
        _ => FieldKind::Text,
    }
}

/// A field name as a prompt label: the schema's `title` when it has one, else
/// the key with its underscores opened up. Both end in a colon, matching the
/// rest of the CLI's prompts.
fn label_for(key: &str, prop: &serde_json::Value) -> String {
    let base = prop
        .get("title")
        .and_then(|t| t.as_str())
        .map(str::to_string)
        .unwrap_or_else(|| {
            let mut words = key.replace('_', " ");
            if let Some(first) = words.get_mut(0..1) {
                first.make_ascii_uppercase();
            }
            words
        });
    format!("{base}:")
}

/// Help text for a field: the schema's `description`, flattened to one line.
/// A multi-line description wraps a terminal prompt into something that scrolls
/// the question itself off the screen.
fn help_for(prop: &serde_json::Value) -> Option<String> {
    prop.get("description")
        .or_else(|| unwrapped(prop).get("description"))
        .and_then(|d| d.as_str())
        .map(|d| d.split_whitespace().collect::<Vec<_>>().join(" "))
        .filter(|d| !d.is_empty())
}

/// A JSON value as a bare string: strings unquoted, everything else compact.
fn scalar(v: &serde_json::Value) -> String {
    v.as_str()
        .map(str::to_string)
        .unwrap_or_else(|| v.to_string())
}

/// The prompt for one property of `schema`, or `None` when the schema does not
/// describe that key at all.
pub fn field_spec(schema: &serde_json::Value, key: &str) -> Option<FieldSpec> {
    let prop = schema.get("properties")?.get(key)?;
    let required = schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|r| r.iter().any(|n| n.as_str() == Some(key)))
        .unwrap_or(false);
    Some(FieldSpec {
        label: label_for(key, prop),
        help: help_for(prop),
        required,
        secret: is_secret_field(key, prop),
        choices: choices(prop),
        // A secret carries no default: a masked prompt showing a pre-filled
        // value reveals its length, and an answer the user never typed is one
        // they cannot see to correct.
        default: match prop.get("default") {
            Some(serde_json::Value::Null) | None => None,
            Some(v) if is_secret_field(key, prop) => {
                let _ = v;
                None
            }
            Some(v) => Some(scalar(v)),
        },
        kind: kind_of(prop),
    })
}

/// Every required property of `schema`, in schema order.
pub fn required_keys(schema: &serde_json::Value) -> Vec<String> {
    schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|r| {
            r.iter()
                .filter_map(|v| v.as_str())
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

/// One half of a request body (a `config` or a `credentials` object) being
/// filled in against its schema.
pub struct Form<'a> {
    schema: &'a serde_json::Value,
    values: serde_json::Map<String, serde_json::Value>,
    handled: Vec<String>,
}

impl<'a> Form<'a> {
    pub fn new(schema: &'a serde_json::Value) -> Self {
        Form {
            schema,
            values: serde_json::Map::new(),
            handled: Vec::new(),
        }
    }

    /// Whether the schema describes this key. Flows read it to decide between
    /// two shapes without guessing which one this build's service serves.
    pub fn has(&self, key: &str) -> bool {
        self.schema
            .get("properties")
            .and_then(|p| p.get(key))
            .is_some()
    }

    /// Whether `value` is one of the values the schema accepts for `key`.
    /// A catalog preset is only a preset while the service still takes it.
    pub fn accepts(&self, key: &str, value: &str) -> bool {
        field_spec(self.schema, key)
            .map(|f| f.choices.is_empty() || f.choices.iter().any(|c| c == value))
            .unwrap_or(false)
    }

    /// Set a value without asking — a catalog preset, or an answer derived from
    /// one already given. Ignored when the schema has no such field.
    pub fn set(&mut self, key: &str, value: serde_json::Value) {
        if !self.has(key) {
            return;
        }
        self.handled.push(key.to_string());
        self.values.insert(key.to_string(), value);
    }

    /// Ask for one field, typed and validated by its schema. A key the schema
    /// does not describe is skipped silently: the flow naming it is a hand-
    /// written list, and asking for a field the API has dropped would collect
    /// an answer only to have the request rejected for carrying it.
    pub fn ask(&mut self, key: &str) {
        self.ask_with(key, |_| {});
    }

    /// Ask for a field the flow knows is needed here even though the schema
    /// marks it optional — a credential the chosen auth type cannot work
    /// without, say. The prompt then refuses a blank answer.
    pub fn ask_required(&mut self, key: &str) {
        self.ask_with(key, |spec| spec.required = true);
    }

    /// Ask, pre-filled with a value the flow derived rather than the schema's
    /// default: a port that follows the dialect, a base URL out of a catalog
    /// template. Offered rather than set, so a derivation that is wrong is
    /// visible on the prompt instead of arriving as a 422.
    pub fn ask_with_default(&mut self, key: &str, default: Option<&str>) {
        let default = default.map(str::to_string);
        self.ask_with(key, move |spec| {
            // A secret is never pre-filled — see `field_spec`.
            if !spec.secret && default.is_some() {
                spec.default = default.clone();
            }
        });
    }

    /// Ask, with help the flow can say and the schema cannot: which blanks are
    /// legitimate answers here, given what has been chosen already.
    pub fn ask_hinted(&mut self, key: &str, help: &str) {
        let help = help.to_string();
        self.ask_with(key, move |spec| {
            spec.help = Some(match &spec.help {
                Some(existing) => format!("{existing} {help}"),
                None => help.clone(),
            })
        });
    }

    /// The answer already collected for `key`, when it is a string. Flows read
    /// it to branch: the provider decides which credential to ask for next.
    pub fn get_str(&self, key: &str) -> Option<String> {
        self.values.get(key)?.as_str().map(str::to_string)
    }

    /// One `ask`, with the schema-derived spec adjusted first.
    fn ask_with(&mut self, key: &str, adjust: impl FnOnce(&mut FieldSpec)) {
        let Some(mut spec) = field_spec(self.schema, key) else {
            return;
        };
        adjust(&mut spec);
        self.handled.push(key.to_string());
        if let Some(value) = ask_field(&spec) {
            self.values.insert(key.to_string(), value);
        }
    }

    /// Fill a deliberately free-form map (`options`, `catalog_config`,
    /// `storage`) from the per-entry key hints the catalog supplies.
    ///
    /// These maps have no properties to read, by design — they carry the knobs
    /// that differ per engine rather than per family. The hint is the service's
    /// own description of which keys this entry wants, so the prompts stay as
    /// service-driven as the schema-backed ones; with no hint there is nothing
    /// truthful to ask and the map is left out.
    pub fn ask_map(&mut self, key: &str, hint: Option<&crate::client::ingest::OptionsHint>) {
        if !self.has(key) {
            return;
        }
        self.handled.push(key.to_string());
        let Some(hint) = hint.filter(|h| h.config_field == key && !h.keys.is_empty()) else {
            return;
        };
        let mut map = serde_json::Map::new();
        let mut names: Vec<&String> = hint.keys.keys().collect();
        names.sort();
        for name in names {
            let answer = prompt::text(
                &format!("{name}:"),
                hint.keys.get(name).map(String::as_str),
                None,
            );
            let answer = answer.trim();
            if !answer.is_empty() {
                map.insert(name.clone(), answer.into());
            }
        }
        if !map.is_empty() {
            self.values.insert(key.to_string(), map.into());
        }
    }

    /// Ask for every required field the flow did not name.
    ///
    /// The safety net for the one drift a per-family flow cannot absorb on its
    /// own: the service making a new field required. Without this the wizard
    /// would build a body missing it and hand the user a 422 about a field it
    /// never mentioned — the failure mode that a hand-written question list is
    /// otherwise guaranteed to reach eventually.
    pub fn ask_remaining_required(&mut self) {
        for key in required_keys(self.schema) {
            if !self.handled.contains(&key) {
                self.ask(&key);
            }
        }
    }

    pub fn is_empty(&self) -> bool {
        self.values.is_empty()
    }

    pub fn finish(self) -> serde_json::Value {
        serde_json::Value::Object(self.values)
    }
}

/// Ask one field and coerce the answer into the type its schema declares.
/// `None` means "leave the key out" — an optional field the user skipped. An
/// empty string is not the same request as an absent key, and for a credential
/// the difference is "no credential" versus "inherit".
fn ask_field(spec: &FieldSpec) -> Option<serde_json::Value> {
    if spec.kind == FieldKind::Boolean {
        let default = spec.default.as_deref() == Some("true");
        return Some(prompt::confirm(&spec.label, default).into());
    }
    if !spec.choices.is_empty() {
        // A menu of the accepted values cannot produce the 422 that typing one
        // of them can. An optional enum gets a way out of the menu, since ESC
        // quits the whole flow rather than skipping one question.
        let mut options = spec.choices.clone();
        if !spec.required {
            options.push(SKIP.to_string());
        }
        let start = spec
            .default
            .as_deref()
            .and_then(|d| options.iter().position(|o| o == d))
            .unwrap_or(0);
        let chosen = &options
            [prompt::select_index(&spec.label, spec.help.as_deref(), &rotated(&options, start))];
        return (chosen != SKIP).then(|| chosen.clone().into());
    }

    loop {
        let raw = if spec.secret {
            prompt::secret(&spec.label, spec.help.as_deref())
        } else {
            prompt::text(&spec.label, spec.help.as_deref(), spec.default.as_deref())
        };
        let raw = raw.trim();
        if raw.is_empty() {
            if spec.required {
                eprintln!("  {} is required.", spec.label.trim_end_matches(':'));
                continue;
            }
            return None;
        }
        return match spec.kind {
            FieldKind::Integer => match raw.parse::<i64>() {
                Ok(n) => Some(n.into()),
                Err(_) => {
                    eprintln!("  {raw} is not a number.");
                    continue;
                }
            },
            FieldKind::StringList => Some(
                raw.split(',')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .collect::<Vec<_>>()
                    .into(),
            ),
            _ => Some(raw.into()),
        };
    }
}

/// The menu entry that leaves an optional field unset.
const SKIP: &str = "(skip)";

/// `options` with `start` first, so a schema default is the highlighted choice
/// without being the only one offered.
fn rotated(options: &[String], start: usize) -> Vec<String> {
    let mut out = options.to_vec();
    let by = start.min(out.len().saturating_sub(1));
    out.rotate_left(by);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The pinned `GET /families/{family}` body — the same bytes the client
    /// test asserts against, so the prompts are derived from a response shape
    /// rather than from a fixture shaped to suit them.
    fn sql() -> serde_json::Value {
        serde_json::from_str(crate::client::ingest::FAMILY_REFERENCE_BODY).unwrap()
    }

    #[test]
    fn a_required_enum_is_asked_as_a_menu_of_the_accepted_values() {
        let spec = field_spec(&sql()["config_schema"], "dialect").unwrap();
        assert_eq!(spec.label, "Dialect:");
        assert!(spec.required);
        assert!(!spec.secret);
        assert_eq!(spec.choices, ["postgres", "mysql", "duckdb"]);
        assert_eq!(spec.kind, FieldKind::Text);
    }

    #[test]
    fn an_optional_field_is_read_through_its_null_union() {
        // Optionals arrive as `anyOf: [T, {"type": "null"}]`. Reading `type`
        // off the outer object finds nothing, which would type every optional
        // field as free text — including the ones that are integers.
        let spec = field_spec(&sql()["config_schema"], "port").unwrap();
        assert!(!spec.required);
        assert_eq!(spec.kind, FieldKind::Integer);
        assert_eq!(spec.default, None);

        let spec = field_spec(&sql()["config_schema"], "host").unwrap();
        assert_eq!(spec.kind, FieldKind::Text);
    }

    #[test]
    fn a_password_formatted_field_is_marked_secret_through_the_union() {
        let creds = sql()["credentials_schema"].clone();
        let password = field_spec(&creds, "password").unwrap();
        assert!(password.secret, "format: password must reach the prompt");
        let username = field_spec(&creds, "username").unwrap();
        assert!(!username.secret);
    }

    #[test]
    fn a_secret_never_carries_a_default() {
        // A masked prompt pre-filled with a value still shows its length, and
        // the user cannot read it to correct it.
        let schema = serde_json::json!({
            "properties": {
                "token": {"type": "string", "format": "password", "default": "hunter2"}
            },
            "type": "object"
        });
        let spec = field_spec(&schema, "token").unwrap();
        assert!(spec.secret);
        assert_eq!(spec.default, None);
    }

    #[test]
    fn a_credential_field_is_hidden_even_when_the_schema_forgets_to_say_so() {
        // The marker travels over the network, and it is the only thing that
        // decides whether the prompt echoes. A field that arrives without it
        // must still be hidden, or a schema regression publishes the user's
        // secret into their scrollback with nothing failing.
        let bare = |name: &str| {
            let schema = serde_json::json!({
                "properties": { name: {"type": "string"} }, "type": "object"
            });
            field_spec(&schema, name).unwrap().secret
        };
        for name in [
            "password",
            "sasl_password",
            "api_key",
            "aws_secret_access_key",
            "azure_storage_account_key",
            "access_token",
            "client_secret",
            "authorization",
        ] {
            assert!(
                bare(name),
                "{name} must be hidden without the schema marker"
            );
        }

        // The public half of a credential pair stays readable. Masking these
        // costs legibility and protects nothing — the service does not mark
        // them either.
        for name in [
            "username",
            "sasl_username",
            "aws_access_key_id",
            "client_id",
            "tenant_id",
            "host",
            "azure_storage_account_name",
        ] {
            assert!(!bare(name), "{name} is an identity field, not a secret");
        }
    }

    #[test]
    fn labels_and_help_come_from_the_schema() {
        let schema = serde_json::json!({
            "properties": {
                "root_uri": {"type": "string", "title": "Root Uri",
                             "description": "Bucket root, e.g. s3://my-bucket.\nKeys are relative to it."},
                "group_id_prefix": {"type": "string"}
            },
            "required": ["root_uri"],
            "type": "object"
        });
        let spec = field_spec(&schema, "root_uri").unwrap();
        assert_eq!(spec.label, "Root Uri:");
        // Flattened: a wrapped description scrolls the question off screen.
        assert_eq!(
            spec.help.as_deref(),
            Some("Bucket root, e.g. s3://my-bucket. Keys are relative to it.")
        );
        // No title: the key itself, opened up.
        assert_eq!(
            field_spec(&schema, "group_id_prefix").unwrap().label,
            "Group id prefix:"
        );
    }

    #[test]
    fn a_field_the_schema_does_not_describe_is_never_asked() {
        // The guard that keeps a hand-written flow from out-living the API: a
        // renamed or dropped field stops being prompted for instead of
        // collecting an answer the request would be rejected for carrying.
        let schema = sql()["config_schema"].clone();
        assert!(field_spec(&schema, "hostname").is_none());
        let mut form = Form::new(&schema);
        form.ask("hostname");
        form.set("hostname", "pg.example.com".into());
        assert!(form.is_empty());
    }

    #[test]
    fn presets_are_only_applied_while_the_service_still_accepts_them() {
        let schema = sql()["config_schema"].clone();
        let form = Form::new(&schema);
        assert!(form.accepts("dialect", "postgres"));
        // A catalog entry naming a dialect this build's service dropped is not
        // a preset — the flow asks instead of sending a value that 422s.
        assert!(!form.accepts("dialect", "informix"));
        // A field with no enum accepts whatever it is given.
        assert!(form.accepts("host", "pg.example.com"));
    }

    #[test]
    fn the_remaining_required_sweep_covers_what_a_flow_named() {
        let schema = sql()["config_schema"].clone();
        let mut form = Form::new(&schema);
        // `dialect` is the schema's only required field; presetting it counts
        // as handled, so the sweep has nothing left to ask and cannot block a
        // non-interactive test on a prompt.
        form.set("dialect", "postgres".into());
        form.ask_remaining_required();
        assert_eq!(form.finish(), serde_json::json!({"dialect": "postgres"}));
    }

    #[test]
    fn free_form_maps_are_filled_only_from_a_hint_for_that_field() {
        let schema = serde_json::json!({
            "properties": {"options": {"type": "object", "additionalProperties": true}},
            "type": "object"
        });
        let hint = crate::client::ingest::OptionsHint {
            config_field: "catalog_config".into(),
            keys: [("uri".to_string(), "Catalog URI".to_string())]
                .into_iter()
                .collect(),
        };
        let mut form = Form::new(&schema);
        // A hint for a different field is not this field's hint — filling
        // `options` from it would put iceberg's catalog knobs on a SQL config.
        form.ask_map("options", Some(&hint));
        assert!(form.is_empty());
        // Nothing to ask when the catalog described no keys.
        let mut form = Form::new(&schema);
        form.ask_map("options", None);
        assert!(form.is_empty());
    }

    #[test]
    fn an_enum_menu_opens_on_the_schema_default() {
        let options: Vec<String> = ["rest", "glue", "hive", "sql"]
            .iter()
            .map(|s| s.to_string())
            .collect();
        assert_eq!(rotated(&options, 0)[0], "rest");
        assert_eq!(rotated(&options, 1), ["glue", "hive", "sql", "rest"]);
    }
}
